Reimplemented insertProduct-function
vincentdelitz/festival-database-with-java pull request #10
Opened 2017-07-17 16:40 UTC by MilenaZurmuehl

Please review the code and merge it to the rest!

2017-07-18 10:44 UTC, vincentdelitz commented
@MilenaZurmuehl can you please add the correct link in the index.htm, so that I can test the functionality.

2017-07-18 13:21 UTC, MilenaZurmuehl commented
@vincentdelitz the link is actually already in the htm-file (but only there, so from other pages it will not work!)! So it should also be in the uploaded version! And regarding the Servlets: these are no versions of the servlets but different ones which we all need!! I you think it is confusing I can rename them so it get' more obvious what they are for!!

2017-07-18 21:47 UTC, morvalgo reviewed
Please do NOT merge it, because I am not sure whether Milena has worked with the version of the branch insertProduct2 that i commited and pushed. I think the error handling that I implemented could be lost if you now merge it. I think Vincent should check it, because he has the best knowledge with git!

2017-07-18 22:34 UTC, vincentdelitz commented
@morvalgo @demirdagemir @brunofiu @Hermionee It works for me now, too, but Moritz functionality with the error handling won't anymore. I think he needs to adapt it to the new structure in the next days. Could anyone of you still please review the code and then approve the pull request?

2017-07-19 15:35 UTC, demirdagemir requested changes
For me the link insert product didn't work. Commented inside the code. Does it work for everyone else? Also we should update the headers because almost all of them has different links.

Other than that the logic works. (Inserting new product/custom product)

2017-07-19 15:35 UTC, demirdagemir commented on BaseProject/WebContent/index.htm
> +			                  <li><a href="./insertProductServlet">Insert new product</a></li>
For me this doesn't work. The servlet annotation is `InsertProductServlet` but it's `insertProductServlet` here. I think it should be capital.

2017-07-19 15:35 UTC, demirdagemir commented on BaseProject/WebContent/successfulInsert.jsp
> +                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Homework Example <span class="caret"></span></a>
We should update this header to the new one

2017-07-19 15:35 UTC, demirdagemir commented on BaseProject/src/de/tum/in/dbpra/InsertProductServlet.java
> +//		int shopID = Integer.parseInt(request.getParameter("shopID"));
We could delete the commented out code

2017-07-19 15:35 UTC, demirdagemir commented on BaseProject/WebContent/enterProduct.jsp
> +                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Homework Example <span class="caret"></span></a>
Same old header here

2017-07-20 09:38 UTC, vincentdelitz commented
@demirdagemir are your requested changes still valid, as you have now "outsourced" the header issues into the header.jsp?

2017-07-21 22:17 UTC, demirdagemir approved these changes

2017-07-21 22:21 UTC, merged